# Generated by Django 5.2.7 on 2025-10-31 01:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Configuration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(choices=[('database', 'Database'), ('ai_model', 'AI Model'), ('ui', 'UI Settings'), ('support', 'Support'), ('vector_search', 'Vector Search'), ('security', 'Security')], help_text='Configuration section', max_length=50)),
                ('key', models.CharField(help_text='Configuration key within the section', max_length=100)),
                ('value', models.JSONField(help_text='Configuration value (can be any JSON-serializable type)')),
                ('description', models.TextField(blank=True, help_text='Human-readable description of this configuration setting')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this configuration setting is active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last updated this configuration', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['section', 'key'],
            },
        ),
        migrations.CreateModel(
            name='ConfigurationHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_value', models.JSONField(blank=True, help_text='Previous configuration value', null=True)),
                ('new_value', models.JSONField(help_text='New configuration value')),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('reason', models.TextField(blank=True, help_text='Reason for the configuration change')),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('configuration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='configuration.configuration')),
            ],
            options={
                'ordering': ['-changed_at'],
            },
        ),
        migrations.CreateModel(
            name='ConfigurationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Template name', max_length=100, unique=True)),
                ('description', models.TextField(blank=True, help_text='Template description')),
                ('configuration_data', models.JSONField(help_text='Complete configuration data as JSON')),
                ('is_default', models.BooleanField(default=False, help_text='Whether this is the default template')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddIndex(
            model_name='configuration',
            index=models.Index(fields=['section'], name='configurati_section_c4850a_idx'),
        ),
        migrations.AddIndex(
            model_name='configuration',
            index=models.Index(fields=['section', 'key'], name='configurati_section_7736af_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='configuration',
            unique_together={('section', 'key')},
        ),
    ]
